version: '3.1'
services:
  stats-server:
    build: stat/stat-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db

  stats-db:
    image: postgres:14.6
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
